import os

file_path = r'c:\Users\adrian.rubio\OneDrive - CENVAL S.L\Escritorio\repositorios\Data_Management\backend\routers\reports.py'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = []
skip = False
for line in lines:
    if 'def get_abc_analysis(' in line:
        new_lines.append(line)
        # We start looking for the next def or end of function
        skip = True
        # Append the new optimized body
        new_lines.append("    page: int = 1,\n")
        new_lines.append("    page_size: int = 50,\n")
        new_lines.append("    search: Optional[str] = None,\n")
        new_lines.append("    division: Optional[str] = None,\n")
        new_lines.append("    tipo2025: Optional[str] = None,\n")
        new_lines.append("    tipo2026: Optional[str] = None,\n")
        new_lines.append("    proveedor: Optional[str] = None,\n")
        new_lines.append("    subfamilia: Optional[str] = None,\n")
        new_lines.append("    sort_by: Optional[str] = None,\n")
        new_lines.append("    sort_order: str = \"desc\",\n")
        new_lines.append("    db: Session = Depends(get_db), \n")
        new_lines.append("    current_user: models.User = Depends(auth.get_current_active_user)\n")
        new_lines.append("):\n")
        new_lines.append("    def check_is_authorized(u):\n")
        new_lines.append("        r_name = str(u.role).lower()\n")
        new_lines.append("        ro_name = str(u.role_obj.name).lower() if u.role_obj else \"\"\n")
        new_lines.append("        return \"admin\" in r_name or \"direcci\" in r_name or \"direccion\" in r_name or \"admin\" in ro_name\n\n")
        new_lines.append("    if not check_is_authorized(current_user):\n")
        new_lines.append("        raise HTTPException(status_code=403, detail=\"Not authorized for this report\")\n\n")
        new_lines.append("    try:\n")
        new_lines.append("        now = datetime.now()\n")
        new_lines.append("        if (ABC_CACHE[\"df\"] is not None and \n")
        new_lines.append("            ABC_CACHE[\"timestamp\"] is not None and \n")
        new_lines.append("            (now - ABC_CACHE[\"timestamp\"]).total_seconds() < CACHE_SECONDS):\n")
        new_lines.append("            df_full = ABC_CACHE[\"df\"]\n")
        new_lines.append("        else:\n")
        new_lines.append("            query_sales = \"\"\"\n")
        new_lines.append("                WITH SalesData AS (\n")
        new_lines.append("                    SELECT \n")
        new_lines.append("                        RTRIM(LTRIM(CodigoArticulo)) as CodigoArticulo,\n")
        new_lines.append("                        SUM(CASE WHEN FechaAlbaran >= '2025-01-01' AND FechaAlbaran < '2026-01-01' THEN Unidades ELSE 0 END) as Venta2025,\n")
        new_lines.append("                        SUM(CASE WHEN FechaAlbaran >= '2026-01-01' AND FechaAlbaran < '2027-01-01' THEN Unidades ELSE 0 END) as Venta2026\n")
        new_lines.append("                    FROM LineasAlbaranCliente WITH (NOLOCK)\n")
        new_lines.append("                    WHERE FechaAlbaran >= '2025-01-01' AND FechaAlbaran < '2027-01-01'\n")
        new_lines.append("                      AND CodigoEmpresa = 2\n")
        new_lines.append("                      AND RTRIM(LTRIM(CodigoArticulo)) NOT IN ('', '.')\n")
        new_lines.append("                    GROUP BY RTRIM(LTRIM(CodigoArticulo))\n")
        new_lines.append("                )\n")
        new_lines.append("                SELECT \n")
        new_lines.append("                    s.CodigoArticulo, a.DescripcionArticulo as Descripcion, a.CodigoFamilia as Familia, \n")
        new_lines.append("                    a.CodigoSubfamilia as Subfamilia, p.RazonSocial as Proveedor, s.Venta2025, s.Venta2026\n")
        new_lines.append("                FROM SalesData s\n")
        new_lines.append("                LEFT JOIN Articulos a WITH (NOLOCK) ON s.CodigoArticulo = a.CodigoArticulo AND a.CodigoEmpresa = 2\n")
        new_lines.append("                LEFT JOIN Proveedores p WITH (NOLOCK) ON a.CodigoProveedor = p.CodigoProveedor AND a.CodigoEmpresa = 2\n")
        new_lines.append("            \"\"\"\n")
        new_lines.append("            df_sales = pd.read_sql(text(query_sales), db.bind)\n")
        new_lines.append("            query_stock = \"\"\"\n")
        new_lines.append("                SELECT RTRIM(LTRIM(CodigoArticulo)) as CodigoArticulo, MAX(UnidadSaldo) as StockActual \n")
        new_lines.append("                FROM PowerBi_AcumuladoStock WITH (NOLOCK)\n")
        new_lines.append("                WHERE CodigoEmpresa = 2\n")
        new_lines.append("                  AND Ejercicio = (SELECT MAX(Ejercicio) FROM PowerBi_AcumuladoStock WHERE CodigoEmpresa = 2)\n")
        new_lines.append("                  AND Periodo = (SELECT MAX(Periodo) FROM PowerBi_AcumuladoStock WHERE CodigoEmpresa = 2 AND Ejercicio = (SELECT MAX(Ejercicio) FROM PowerBi_AcumuladoStock WHERE CodigoEmpresa = 2))\n")
        new_lines.append("                GROUP BY CodigoArticulo\n")
        new_lines.append("            \"\"\"\n")
        new_lines.append("            df_stock = pd.read_sql(text(query_stock), db.bind)\n")
        new_lines.append("            df = pd.merge(df_sales, df_stock, on='CodigoArticulo', how='left').fillna(0)\n")
        new_lines.append("            df['Division'] = df['Familia'].apply(map_division).fillna('Otros')\n\n")
        new_lines.append("            def apply_abc(target_df, val_col, pct_col, type_col):\n")
        new_lines.append("                w_df = target_df.sort_values(by=val_col, ascending=False).copy()\n")
        new_lines.append("                total_val = w_df[val_col].sum()\n")
        new_lines.append("                if total_val > 0:\n")
        new_lines.append("                    w_df[pct_col] = (w_df[val_col] / total_val) * 100\n")
        new_lines.append("                    c_pct = w_df[pct_col].cumsum()\n")
        new_lines.append("                    w_df[type_col] = c_pct.apply(lambda cp: 'A' if cp <= 80.001 else ('B' if cp <= 96.001 else 'C'))\n")
        new_lines.append("                else:\n")
        new_lines.append("                    w_df[pct_col] = 0.0\n")
        new_lines.append("                    w_df[type_col] = 'C'\n")
        new_lines.append("                return w_df\n\n")
        new_lines.append("            df_2025 = apply_abc(df, 'Venta2025', 'Porcentaje2025', 'Tipo2025')\n")
        new_lines.append("            df_2026 = apply_abc(df, 'Venta2026', 'Porcentaje2026', 'Tipo2026')\n")
        new_lines.append("            df_full = pd.merge(\n")
        new_lines.append("                df_2025[['CodigoArticulo', 'Descripcion', 'Familia', 'Subfamilia', 'Division', 'Proveedor', 'Venta2025', 'Porcentaje2025', 'Tipo2025', 'StockActual']],\n")
        new_lines.append("                df_2026[['CodigoArticulo', 'Venta2026', 'Porcentaje2026', 'Tipo2026']],\n")
        new_lines.append("                on='CodigoArticulo'\n")
        new_lines.append("            )\n")
        new_lines.append("            cols_order = ['CodigoArticulo', 'Descripcion', 'Familia', 'Subfamilia', 'Proveedor', 'Division', 'Venta2025', 'Porcentaje2025', 'Tipo2025', 'Venta2026', 'Porcentaje2026', 'Tipo2026', 'StockActual']\n")
        new_lines.append("            df_full = df_full[cols_order]\n")
        new_lines.append("            ABC_CACHE[\"df\"] = df_full\n")
        new_lines.append("            ABC_CACHE[\"timestamp\"] = now\n\n")
        new_lines.append("        res = df_full.copy()\n")
        new_lines.append("        if search:\n")
        new_lines.append("            search = search.lower()\n")
        new_lines.append("            res = res[res['CodigoArticulo'].str.lower().str.contains(search) | res['Descripcion'].str.lower().str.contains(search)]\n")
        new_lines.append("        if division: res = res[res['Division'] == division]\n")
        new_lines.append("        if tipo2025: res = res[res['Tipo2025'] == tipo2025]\n")
        new_lines.append("        if tipo2026: res = res[res['Tipo2026'] == tipo2026]\n")
        new_lines.append("        if proveedor: res = res[res['Proveedor'] == proveedor]\n")
        new_lines.append("        if subfamilia: res = res[res['Subfamilia'] == subfamilia]\n")
        new_lines.append("        if sort_by and sort_by in res.columns:\n")
        new_lines.append("            res = res.sort_values(by=sort_by, ascending=(sort_order == \"asc\"))\n\n")
        new_lines.append("        total = len(res)\n")
        new_lines.append("        start = (page - 1) * page_size\n")
        new_lines.append("        end = start + page_size\n")
        new_lines.append("        paginated_data = res.iloc[start:end].to_dict('records')\n")
        new_lines.append("        return {\"data\": paginated_data, \"total\": total, \"page\": page, \"page_size\": page_size, \"total_pages\": math.ceil(total / page_size)}\n")
        new_lines.append("    except Exception as e:\n")
        new_lines.append("        print(f\"Error checking ABC Analysis logic: {e}\")\n")
        new_lines.append("        raise HTTPException(status_code=500, detail=str(e))\n")
        continue

    if skip:
        # Stop skipping once we hit the next endpoint or end of file
        if '@router.' in line:
            skip = False
            new_lines.append(line)
        continue
    
    new_lines.append(line)

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
print("SUCCESS")
